[WIP] updates to service and generator
GregYankovoy/vue-cli-plugin-bootstrap-vue pull request #1
Opened 2019-05-05 22:53 UTC by tmorehouse

WIP

2019-05-06 23:19 UTC, GregYankovoy commented
Everything looks good except the @latest tag.  Latest version of @vue/cli does not seem to accept it as a valid version, and as a result does not append it to the package.json dependencies section.  

Test steps:
1. Pulled your branch 
2. Created new vue-cli project via "vue create testproj"
3. Added vue-cli-plugin-bootstrap-vue via npm install --save-dev yourBranch
4. vue invoke vue-cli-plugin-bootstrap-vue 
5. Console outputs the below
` WARN  invalid version range for dependency "bootstrap-vue":

- @latest injected by generator "vue-cli-plugin-bootstrap-vue"`

2019-05-06 23:43 UTC, tmorehouse commented
Interesting on the `@latest` (which works in regular package.json files).

It is a shame to tie it to the `^2.0.0-rc.xx` versions, as usually `yarn upgrade` (or similar) will not update to the non `rc.xx` release when it becomes available (hopefully within the next few weeks or so we should be at `2.0.0` stable).

2019-05-06 23:47 UTC, GregYankovoy commented
Agreed that it's a bit of a shame.  I wonder if the motivation has to do w/ how the vue-cli works, encouraging people to upgrade via the vue-cli toolset (or if they just haven't adapted to the @latest tag yet).

Should we hold off on any changes until the project reaches a stable version?  Perhaps we want to explore a complete overhaul.  I noticed vuetify supports automatic a la carte via their "vuetify-loader".

2019-05-06 23:53 UTC, tmorehouse commented
I based some of my code off of Vuetify, and have also some presets (i.e using SCSS vs CSS), and options for aliasing the Vue import (so that PortalVue/BoostrapVue/and others) import the same Vue module (to prevent `$listeners is readonly` errors).

We don't have a direct equvalent to their `a-la-carte` mode, but we do have options for importing only the config setting module (without needing to load the entire BootstrapVue library).  users would need to import components where they need them).  Or we could have an option to do selective component group plugin imports, like we have with the Nuxt.js module.

2019-05-06 23:56 UTC, tmorehouse commented
`2.0.0-rc.20` will be out this week, and the next RC release will have the new tooltip/popover components (using PortalVue), and once the bugs are out of those two, we should have 2.0.0 stable.

2019-05-07 00:08 UTC, GregYankovoy commented
Sounds fairly soon then.  Would you rather I keep the main branch up to date with the RC's until everything is ready?  Or do you want to push through some of your vue.config.js & logo changes in the interim?

I'm okay either way so just let me know and we can work to get them tied into master.

2019-05-07 00:11 UTC, tmorehouse commented
We're updating the logo in RC.20, so it would be nice to match that, and the added component `src` prop resolving is a bonus that will be good for many users.

You can change back to `^2.0.0-rc.19` for the version instead of `@latest`

2019-05-07 00:12 UTC, tmorehouse commented
Once I get a bit more time, I'll pass some vue-cli code ideas by you to see what you think or what can be improved.

2019-05-07 00:39 UTC, tmorehouse commented
Just noticed that vue-cli auto include selective babel polyfils https://cli.vuejs.org/guide/browser-compatibility.html#polyfills

I'm wondering if the injection of the `@babel/polyfil` import is needed or not in the plugin?  if not then it can be removed, but should still have an option to include Mutation Observer shim (needed for IE 11 support, and a few other older browsers)

2019-05-07 00:50 UTC, GregYankovoy commented
If I recall correctly, this config of the babel polyfill was necessary for vuetify & bootstrap-vue.  I believe the issue is that in some situations the necessary polyfills don't get included for IE11 (resulting in a white screen).

2019-05-07 00:51 UTC, GregYankovoy requested changes

2019-05-07 00:51 UTC, GregYankovoy commented on generator/index.js
> +      bootstrap: '^4.3.1',
single quotes

2019-05-07 01:22 UTC, GregYankovoy approved these changes

2019-05-08 02:58 UTC, merged